export const PRODUCTLIST_FAIL = 'PRODUCTLIST_FAIL';
export const PRODUCTLIST_SUCCESS = 'PRODUCTLIST_SUCCESS';
export const PRODUCTLIST_LOADING = 'PRODUCTLIST_LOADING';

export const PRODUCTDETAIL_FAIL = 'PRODUCTDETAIL_FAIL';
export const PRODUCTDETAIL_SUCCESS = 'PRODUCTDETAIL_SUCCESS';
export const PRODUCTDETAIL_LOADING = 'PRODUCTDETAIL_LOADING';
